
-- Q1: Count of Each Event Type
SELECT event_type, COUNT(*) AS total_events
FROM small_file
GROUP BY event_type
ORDER BY total_events DESC;

-- Q2: Top 10 Most Purchased Products
SELECT product_id, COUNT(*) AS purchase_count
FROM small_file
WHERE event_type = 'purchase'
GROUP BY product_id
ORDER BY purchase_count DESC
LIMIT 10;

-- Q3: Category-wise Purchase Distribution
SELECT category_id, COUNT(*) AS total_purchases
FROM small_file
WHERE event_type = 'purchase'
GROUP BY category_id
ORDER BY total_purchases DESC;

-- Q4: Revenue Generated by Each Product
SELECT product_id, ROUND(SUM(price), 2) AS total_revenue
FROM small_file
WHERE event_type = 'purchase'
GROUP BY product_id
ORDER BY total_revenue DESC;

-- Q5: Monthly Purchase Trend
SELECT
  DATE_FORMAT(event_time, '%Y-%m') AS month,
  COUNT(*) AS total_purchases
FROM small_file
WHERE event_type = 'purchase'
GROUP BY month
ORDER BY month;
